system:
  version: "1.0.0"
  log_level: "INFO"
  log_file: "logs/assistant.log"
  data_dir: "data"
  feedback_db: "data/feedback.db"
  conversation_dir: "data/conversations"
  rlhf_export_dir: "data/rlhf_exports"
  config_dir: "config"

ollama:
  base_url: "http://localhost:11434"
  timeout: 30
  retry_attempts: 3

assistant:
  default_max_tokens: 1024
  default_temperature: 0.7
  conversation_history_limit: 100

api:
  enabled: false
  port: 8000
  host: "0.0.0.0"#"127.0.0.1"
  auth_required: true

models:
  - name: "gemma3:27b"
    role: "gemma3_27b"
    system_prompt: |
      你是中国烹饪协会认证的专业厨师与注册营养师。你的目标是为中国18岁至30岁的低等劳动程度的男性优化食谱的营养素总含量。
      针对输入的食谱，仅改变食材用量，不改变食材名称。
      输出仅包括食材名称及食材用量（克）。食材之间用半角逗号隔开（半角逗号后无任何' '与'\n'）。食材用量必须只能精确到小数点后一位。
      输出必须不包含任何计算、推理、建议等多余文字。必须用中文回答。
    strengths:
      analysis: 0.95
      critical_thinking: 0.9
      reasoning: 0.92
      evaluation: 0.88
      problem_solving: 0.85
      language: 0.8

  - name: "qwq:32b-nothink"
    role: "qwq_32b_nothink"
    system_prompt: |
      你是中国烹饪协会认证的专业厨师与注册营养师。
      针对输入的食谱，仅改变食材用量，不改变食材名称。
      输出仅包括食材名称及食材用量（克）。食材之间用半角逗号隔开（半角逗号后无任何' '与'\n'）。食材用量必须只能精确到小数点后一位。
      输出必须不包含任何计算、推理、建议等多余文字。必须用中文回答。

    strengths:
      analysis: 1
      critical_thinking: 1
      reasoning: 1
      evaluation: 1
      problem_solving: 1
      language: 0.8

  - name: "deepseek-r1:32b-nothink"
    role: "deepseek_r1_32b_nothink"
    system_prompt: |
      你是中国烹饪协会认证的专业厨师与注册营养师。
      针对输入的食谱，仅改变食材用量，不改变食材名称。
      输出仅包括食材名称及食材用量（克）。食材之间用半角逗号隔开（半角逗号后无任何' '与'\n'）。食材用量必须只能精确到小数点后一位。
      输出必须不包含任何计算、推理、建议等多余文字。输出必须用中文。

    strengths:
      analysis: 1
      critical_thinking: 0.8
      reasoning: 1
      evaluation: 1
      problem_solving: 0.8
      language: 0.8
