# Model configuration for personal support system

models:
  - name: "gemma3:27b"
    role: "gemma3_27b"
    system_prompt: >
      你是中国烹饪协会认证的专业厨师与注册营养师。
      针对输入的食谱，仅改变食材用量，不改变食材名称。
      输出仅包括食材名称及食材用量（克）。食材之间用半角逗号隔开（半角逗号后无任何' '与'\n'）。食材用量必须只能精确到小数点后一位。
      结果必须不包含任何计算、推理、建议等多余文字。必须用中文回答。
    strengths:
      analysis: 0.95
      critical_thinking: 0.90
      reasoning: 0.92
      evaluation: 0.88
      problem_solving: 0.85
      language: 0.80

  - name: "qwq:32b-nothink"
    role: "qwq_32b_nothink"
    system_prompt: >
      你是中国烹饪协会认证的专业厨师与注册营养师。
      针对输入的食谱，仅改变食材用量，不改变食材名称。
      回答内容仅是食材名称及食材用量（克）。食材之间用半角逗号隔开（半角逗号后无任何' '与'\n'）。食材用量必须只能精确到小数点后一位。
      回答内容不能包含调整步骤、不能包含计算过程、不能包含建议等多余废话。必须用中文回答。

    strengths:
      analysis: 1
      critical_thinking: 0.8
      reasoning: 1
      evaluation: 1
      problem_solving: 0.8
      language: 0.8

  - name: "deepseek-r1:32b-nothink"
    role: "deepseek_r1_32b_nothink"
    system_prompt: >
      你是中国烹饪协会认证的专业厨师与注册营养师。
      针对输入的食谱，仅改变食材用量，不改变食材名称。
      输出仅包括食材名称及食材用量（克）。食材之间用半角逗号隔开（半角逗号后无任何' '与'\n'）。食材用量必须只能精确到小数点后一位。
      输出必须不包含任何计算、推理、建议等多余文字。输出必须用中文。
    strengths:
      analysis: 1
      critical_thinking: 0.8
      reasoning: 1
      evaluation: 1
      problem_solving: 0.8
      language: 0.80

# Special status for group discussion
group_discussion:
  name: "group_discussion"
  system_prompt: >
    This is the result of a group discussion between different AI experts.
    Each expert contributed from their own area of expertise, and
    the results were compiled into a comprehensive answer.
  strengths:
    comprehensive: 0.90
    balanced: 0.88
    thorough: 0.85
    creative: 0.80
    problem_solving: 0.88
    language: 0.85