## Prompt templates for each role and question type
#
#code:
#  programming: |
#    Write high-quality source code to solve the following problem.
#    Focus on correctness, efficiency, maintainability, and thorough commenting:
#
#    ${query}
#
#    Notes:
#    1. Ensure the code follows clean code principles
#    2. Add clear and detailed comments
#    3. Handle edge cases and exceptions
#    4. Provide usage examples
#    5. Explain important design choices
#
#  algorithms: |
#    Analyze and implement an algorithm to solve the following problem.
#    Evaluate time and space complexity, along with detailed analysis:
#
#    ${query}
#
#    Requirements:
#    1. Clearly describe the steps of the algorithm
#    2. Analyze the algorithm's complexity (Big O)
#    3. Compare with alternative solutions (if applicable)
#    4. Implement the algorithm in code
#    5. Discuss edge cases and optimizations
#
#  technical_explanation: |
#    Provide a detailed explanation of the following technical aspect.
#    Offer deep, accurate, and comprehensive insights:
#
#    ${query}
#
#    In your explanation, please:
#    1. Start with an easy-to-understand overview
#    2. Dive into technical details
#    3. Explain foundational concepts
#    4. Provide concrete examples
#    5. Highlight practical considerations
#
#  default: |
#    Provide a detailed, technical, and accurate response to the following issue:
#
#    ${query}
#
#    In your response, include:
#    1. Detailed technical explanations
#    2. Concrete examples and source code (if applicable)
#    3. Alternative approaches
#    4. Performance and security considerations
#    5. References or sources (if applicable)
#
#gemma3_27b:
#  analysis: |
#    Conduct a deep and comprehensive analysis of the following issue, considering multiple perspectives:
#
#    ${query}
#
#    In your analysis, include:
#    1. Different aspects of the issue
#    2. Underlying assumptions and their impact on outcomes
#    3. Cause-and-effect relationships
#    4. Evaluation of sustainability and long-term impacts
#    5. Consideration of uncertainties and risks
#    6. Balanced and thoughtful conclusions
#
#qwen3_30b_nothink:
#  analysis: |
#    Conduct a deep and comprehensive analysis of the following issue, considering multiple perspectives:
#
#    ${query}
#
#    In your analysis, include:
#    1. Different aspects of the issue
#    2. Underlying assumptions and their impact on outcomes
#    3. Cause-and-effect relationships
#    4. Evaluation of sustainability and long-term impacts
#    5. Consideration of uncertainties and risks
#    6. Balanced and thoughtful conclusions
#
#qwq_32b_nothink:
#  analysis: |
#    Conduct a deep and comprehensive analysis of the following issue, considering multiple perspectives:
#
#    ${query}
#
#    In your analysis, include:
#    1. Different aspects of the issue
#    2. Underlying assumptions and their impact on outcomes
#    3. Cause-and-effect relationships
#    4. Evaluation of sustainability and long-term impacts
#    5. Consideration of uncertainties and risks
#    6. Balanced and thoughtful conclusions
#
#  critical_thinking: |
#    Apply critical thinking to evaluate the following issue, challenge assumptions,
#    and consider arguments from multiple sides:
#
#    ${query}
#
#    In your analysis, please:
#    1. Identify and validate key assumptions
#    2. Assess the quality and reliability of arguments
#    3. Look for logical flaws or biases
#    4. Consider alternative viewpoints
#    5. Weigh ethical and social implications (if applicable)
#    6. Propose a balanced approach
#
#  evaluation: |
#    Provide a comprehensive evaluation of the following topic, considering strengths, weaknesses,
#    and evidence-based conclusions:
#
#    ${query}
#
#    In your evaluation, include:
#    1. Clear evaluation criteria
#    2. Analysis of pros and cons
#    3. Comparison with alternatives
#    4. Supporting evidence and data
#    5. Contextual and situational considerations
#    6. Conclusions and recommendations based on analysis
#
#  default: |
#    Reflect deeply on the following question, evaluate it from multiple perspectives, and provide
#    a balanced, thorough, and insightful response:
#
#    ${query}
#
#    In your response, please:
#    1. Provide multidimensional analysis
#    2. Consider contradictions and paradoxes
#    3. Connect to broader contexts
#    4. Weigh short-term and long-term consequences
#    5. Offer deep and thoughtful conclusions
#
#deep_thinking8b:
#  analysis: |
#    Conduct a deep and comprehensive analysis of the following issue, considering multiple perspectives:
#
#    ${query}
#
#    In your analysis, include:
#    1. Different aspects of the issue
#    2. Underlying assumptions and their impact on outcomes
#    3. Cause-and-effect relationships
#    4. Evaluation of sustainability and long-term impacts
#    5. Consideration of uncertainties and risks
#    6. Balanced and thoughtful conclusions
#
#  critical_thinking: |
#    Apply critical thinking to evaluate the following issue, challenge assumptions,
#    and consider arguments from multiple sides:
#
#    ${query}
#
#    In your analysis, please:
#    1. Identify and validate key assumptions
#    2. Assess the quality and reliability of arguments
#    3. Look for logical flaws or biases
#    4. Consider alternative viewpoints
#    5. Weigh ethical and social implications (if applicable)
#    6. Propose a balanced approach
#
#  evaluation: |
#    Provide a comprehensive evaluation of the following topic, considering strengths, weaknesses,
#    and evidence-based conclusions:
#
#    ${query}
#
#    In your evaluation, include:
#    1. Clear evaluation criteria
#    2. Analysis of pros and cons
#    3. Comparison with alternatives
#    4. Supporting evidence and data
#    5. Contextual and situational considerations
#    6. Conclusions and recommendations based on analysis
#
#  default: |
#    Reflect deeply on the following question, evaluate it from multiple perspectives, and provide
#    a balanced, thorough, and insightful response:
#
#    ${query}
#
#    In your response, please:
#    1. Provide multidimensional analysis
#    2. Consider contradictions and paradoxes
#    3. Connect to broader contexts
#    4. Weigh short-term and long-term consequences
#    5. Offer deep and thoughtful conclusions
#
#deepseek_r1_32b_nothink:
#  analysis: |
#    Conduct a deep and comprehensive analysis of the following issue, considering multiple perspectives:
#
#    ${query}
#
#    In your analysis, include:
#    1. Different aspects of the issue
#    2. Underlying assumptions and their impact on outcomes
#    3. Cause-and-effect relationships
#    4. Evaluation of sustainability and long-term impacts
#    5. Consideration of uncertainties and risks
#    6. Balanced and thoughtful conclusions
#
#  critical_thinking: |
#    Apply critical thinking to evaluate the following issue, challenge assumptions,
#    and consider arguments from multiple sides:
#
#    ${query}
#
#    In your analysis, please:
#    1. Identify and validate key assumptions
#    2. Assess the quality and reliability of arguments
#    3. Look for logical flaws or biases
#    4. Consider alternative viewpoints
#    5. Weigh ethical and social implications (if applicable)
#    6. Propose a balanced approach
#
#  evaluation: |
#    Provide a comprehensive evaluation of the following topic, considering strengths, weaknesses,
#    and evidence-based conclusions:
#
#    ${query}
#
#    In your evaluation, include:
#    1. Clear evaluation criteria
#    2. Analysis of pros and cons
#    3. Comparison with alternatives
#    4. Supporting evidence and data
#    5. Contextual and situational considerations
#    6. Conclusions and recommendations based on analysis
#
#  default: |
#    Reflect deeply on the following question, evaluate it from multiple perspectives, and provide
#    a balanced, thorough, and insightful response:
#
#    ${query}
#
#    In your response, please:
#    1. Provide multidimensional analysis
#    2. Consider contradictions and paradoxes
#    3. Connect to broader contexts
#    4. Weigh short-term and long-term consequences
#    5. Offer deep and thoughtful conclusions
#
#deep_thinking70b:
#  analysis: |
#    Conduct a deep and comprehensive analysis of the following issue, considering multiple perspectives:
#
#    ${query}
#
#    In your analysis, include:
#    1. Different aspects of the issue
#    2. Underlying assumptions and their impact on outcomes
#    3. Cause-and-effect relationships
#    4. Evaluation of sustainability and long-term impacts
#    5. Consideration of uncertainties and risks
#    6. Balanced and thoughtful conclusions
#
#  critical_thinking: |
#    Apply critical thinking to evaluate the following issue, challenge assumptions,
#    and consider arguments from multiple sides:
#
#    ${query}
#
#    In your analysis, please:
#    1. Identify and validate key assumptions
#    2. Assess the quality and reliability of arguments
#    3. Look for logical flaws or biases
#    4. Consider alternative viewpoints
#    5. Weigh ethical and social implications (if applicable)
#    6. Propose a balanced approach
#
#  evaluation: |
#    Provide a comprehensive evaluation of the following topic, considering strengths, weaknesses,
#    and evidence-based conclusions:
#
#    ${query}
#
#    In your evaluation, include:
#    1. Clear evaluation criteria
#    2. Analysis of pros and cons
#    3. Comparison with alternatives
#    4. Supporting evidence and data
#    5. Contextual and situational considerations
#    6. Conclusions and recommendations based on analysis
#
#  default: |
#    Reflect deeply on the following question, evaluate it from multiple perspectives, and provide
#    a balanced, thorough, and insightful response:
#
#    ${query}
#
#    In your response, please:
#    1. Provide multidimensional analysis
#    2. Consider contradictions and paradoxes
#    3. Connect to broader contexts
#    4. Weigh short-term and long-term consequences
#    5. Offer deep and thoughtful conclusions
#
#llm:
#  summarization: |
#    Provide a concise, informative, and comprehensive summary of:
#
#    ${query}
#
#    The summary should:
#    1. Include the most important key points
#    2. Omit non-essential details
#    3. Be presented in a clear structure
#    4. Not exceed 5 key points
#    5. Use precise and effective language
#
#  conciseness: |
#    Provide a concise and to-the-point answer to the following question:
#
#    ${query}
#
#    Requirements:
#    1. Maximum of 3-5 sentences
#    2. Provide only essential information
#    3. Avoid lengthy explanations
#    4. Use precise language
#    5. Focus on the core of the answer
#
#  default: |
#    Provide a short, clear, and effective response to:
#
#    ${query}
#
#    The response should:
#    1. Get straight to the point
#    2. Use simple and understandable language
#    3. Focus on essential information
#    4. Have a clear structure
#    5. Be easy to digest
#
#group_discussion:
#  complex_problem: |
#    Analyze the following complex problem from multiple professional perspectives.
#    Consider technical aspects, strategic analysis, and practical considerations:
#
#    ${query}
#
#    Requirements for the response:
#    1. Detailed technical analysis from a programmer's perspective
#    2. Critical evaluation from a systems thinking perspective
#    3. Clear and concise summary of key points
#    4. Balance between theory and practical application
#    5. Integration of perspectives into a holistic solution
#
#  default: |
#    Carefully consider the following issue from multiple perspectives, examining technical aspects,
#    deep analysis, and clear presentation:
#
#    ${query}
#
#    In your response, please:
#    1. Provide both technical information and deep analysis
#    2. Consider different viewpoints
#    3. Propose practical and well-founded solutions
#    4. Balance technical detail and accessibility
#    5. Synthesize into a comprehensive and coherent response


# 每个角色和问题类型的提示模板

code:
  programming: |
    编写高质量源代码以解决以下问题。
    注重正确性、效率、可维护性，并提供详尽注释：

    ${query}

    注意事项：
    1. 确保代码符合清晰代码原则
    2. 添加清晰、详细的注释
    3. 处理边界情况和异常
    4. 提供使用示例
    5. 解释重要的设计选择

  algorithms: |
    分析并实现一个算法来解决以下问题。
    评估时间和空间复杂度，并进行详细分析：

    ${query}

    要求：
    1. 清晰描述算法步骤
    2. 分析算法的复杂度（大 O 表示法）
    3. 与其他替代方案进行比较（如适用）
    4. 用代码实现该算法
    5. 讨论边界情况和优化策略

  technical_explanation: |
    对以下技术方面进行详细说明。
    提供深入、准确且全面的见解：

    ${query}

    在你的说明中，请：
    1. 从易于理解的概述开始
    2. 深入技术细节
    3. 解释基础概念
    4. 提供具体示例
    5. 强调实际应用方面的考量

  default: |
    针对以下问题，提供详细、技术性强且准确的答复：

    ${query}

    在你的回答中，请包括：
    1. 详细的技术解释
    2. 具体示例和源代码（如适用）
    3. 替代方法的比较
    4. 性能与安全性方面的考虑
    5. 参考资料或来源（如适用）

gemma3_27b:
  analysis: |
    对以下问题进行深入且全面的分析，考虑多个角度：

    ${query}

    在你的分析中，请包括：
    1. 该问题的不同方面
    2. 潜在假设及其对结果的影响
    3. 因果关系
    4. 可持续性和长期影响的评估
    5. 不确定性和风险的考虑
    6. 平衡且有深度的结论

qwen3_30b_nothink:
  analysis: |
    对以下问题进行深入且全面的分析，考虑多个角度：

    ${query}

    在你的分析中，请包括：
    1. 该问题的不同方面
    2. 潜在假设及其对结果的影响
    3. 因果关系
    4. 可持续性和长期影响的评估
    5. 不确定性和风险的考虑
    6. 平衡且有深度的结论

qwq_32b_nothink:
  analysis: |
    对以下问题进行深入且全面的分析，考虑多个角度：

    ${query}

    在你的分析中，请包括：
    1. 该问题的不同方面
    2. 潜在假设及其对结果的影响
    3. 因果关系
    4. 可持续性和长期影响的评估
    5. 不确定性和风险的考虑
    6. 平衡且有深度的结论


deepseek_r1_32b_nothink:
  analysis: |
    对以下问题进行深入且全面的分析，考虑多个角度：

    ${query}

    在你的分析中，请包括：
    1. 问题涉及的不同维度或层面
    2. 关键的因果关系
    3. 全文用中文分析和表达


deep_thinking70b:
  analysis: |
    对以下问题进行深入且全面的分析，考虑多个角度：

    ${query}

    在你的分析中，请包括：
    1. 该问题的不同方面
    2. 潜在假设及其对结果的影响
    3. 因果关系
    4. 可持续性和长期影响的评估
    5. 不确定性和风险的考虑
    6. 平衡且有深度的结论

  critical_thinking: |
    运用批判性思维来评估以下问题，质疑假设，
    并考虑来自多方面的论点：

    ${query}

    在你的分析中，请：
    1. 识别并验证关键假设
    2. 评估论点的质量和可靠性
    3. 查找逻辑漏洞或偏见
    4. 考虑替代观点
    5. 权衡道德和社会影响（如适用）
    6. 提出一个平衡的方法

  evaluation: |
    对以下主题进行全面评估，考虑其优点、缺点，
    并基于证据得出结论：

    ${query}

    在你的评估中，请包括：
    1. 明确的评估标准
    2. 利弊分析
    3. 与替代方案的比较
    4. 支持性证据和数据
    5. 上下文和情境因素的考量
    6. 基于分析的结论与建议

  default: |
    深入思考以下问题，从多个角度进行评估，并提供
    平衡、全面且富有洞察力的回答：

    ${query}

    在你的回答中，请：
    1. 提供多维度分析
    2. 考虑矛盾与悖论
    3. 联系更广泛的背景
    4. 权衡短期与长期后果
    5. 提供深刻而有思考性的结论

llm:
  summarization: |
    请对以下内容进行简洁、信息丰富且全面的总结：

    ${query}

    总结应当：
    1. 包含最重要的关键点
    2. 省略非关键细节
    3. 结构清晰
    4. 不超过5个要点
    5. 使用精准有效的语言

  conciseness: |
    请对以下问题提供简明扼要的回答：

    ${query}

    要求：
    1. 最多3-5句话
    2. 只提供必要信息
    3. 避免冗长解释
    4. 使用准确语言
    5. 聚焦核心问题

  default: |
    请对以下内容给出简短、清晰且有效的答复：

    ${query}

    回答应当：
    1. 直奔主题
    2. 使用简单易懂的语言
    3. 聚焦关键信息
    4. 结构清晰
    5. 易于理解

group_discussion:
  complex_problem: |
    从多个专业角度分析以下复杂问题。
    考虑技术方面、战略分析和实践可行性：

    ${query}

    回答要求：
    1. 从程序员角度进行详细技术分析
    2. 从系统思维角度进行批判性评估
    3. 对关键点进行简明总结
    4. 理论与实践相结合
    5. 综合多角度形成整体解决方案

  default: |
    仔细从多个角度考虑以下问题，审视技术细节、
    深入分析并清晰表达：

    ${query}

    在你的回答中，请：
    1. 提供技术信息与深入分析
    2. 考虑不同观点
    3. 提出可行且有依据的解决方案
    4. 平衡技术深度与可理解性
    5. 综合成一个全面、连贯的回答